#!/bin/sh
#echo "pull from git..."
#git pull origin develop
killall -9 skynet
echo "start harbor skynet"
cd ./skynet
nohup ./skynet ../servers/meme/component_2  &

ps -ef |grep skynet
echo "start success"
